# Question

Is this function safe? Why or why not?

```js
const getUser = async (userId) => {
  const url = `https://jsonplaceholder.typicode.com/users/${userId}`;
  const response = await fetch(url);
  const users = await response.json();
  console.log(users);
  return users;
};
getUser(-1);
```

Again, running the code gives you the answer, so try to figure it out on your own first!

# Answer

This code is not safe because there is not catch for the case that the user ID does not exist.

# Teacher Feedback
